baseURL = "https://jlevesy.github.io/glaise"

disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]
defaultContentLanguage = "fr"
theme = "hugo-scroll"
title = "Bienvenue au gite de Glaise"

[params]
  copyright = "© Glaise 2020"
  description = "Site web du Gite de Glaise"
  favicon = "images/favicon.png"
  images = ["images/cover-image.jpg"]
  title = "Bienvenue au gite de Glaise"
  [params.meta]
    keywords = "gite, glaise, alpes, Annecy"
